### ISSUE TITLE
Strange behavior when rotating with some angle values

### ISSUE THREAD

**Issue by leyan** [cetz-package/cetz#661] opened 2024-07-28 13:06 UTC
I am getting strange behaviors when rotating around anchors in my pictures, and it seems to be linked to some angles values. Below is a minimal example:
* Set an anchor to (0,1)
* Rotate around this anchor
* Look at the coordinates of the anchor, for example by drawing a circle centered on this anchor

Most of the time, the anchor does not change position, which is to be expected as we rotate around it. However, in several cases the circle is drawn quite far from the expected location. Is it due to numerical imprecisions? 

```Typst
== 64 degrees

#cetz.canvas(length:4cm,{
   group(name:"group",{
    anchor("rotation-center",(0,1))
   })
   group(name:"group2",{
    circle(fill:red,stroke:none,radius:(0.02),"group.rotation-center")
    rotate( 64deg,origin:(0,1))
    line(stroke:0.05mm,(0,0),("group.rotation-center"))
    circle(fill:green,stroke:none,radius:(0.01),"group.rotation-center")
  })
})
== 65 degrees

#cetz.canvas(length:4cm,{
   group(name:"group",{
    anchor("rotation-center",(0,1))
   })
   group(name:"group2",{
    circle(fill:red,stroke:none,radius:(0.02),"group.rotation-center")
    rotate( 65deg,origin:(0,1))
    line(stroke:0.05mm,(0,0),("group.rotation-center"))
    circle(fill:green,stroke:none,radius:(0.01),"group.rotation-center")
  })
})


== loop every 5 degrees

#let test-rotation(angle) = {
   group(name:"group",{
    anchor("rotation-center",(0,1))
   })
   group(name:"group2",{
    circle(fill:red,stroke:none,radius:(0.02),"group.rotation-center")
    rotate( angle,origin:(0,1))
    line(stroke:0.05mm,(0,0),("group.rotation-center"))
    circle(fill:green,stroke:none,radius:(0.01),"group.rotation-center")
    content((rel:(0.2mm,0.2mm),to:(0,0)),text(1pt,[#angle]))
  })
}

#cetz.canvas(length:4cm,{
   import cetz.draw: *
   for i in range(0,360,step:5) {
    test-rotation(i*1deg) 
   } 
})
```

![cetz_tests](https://github.com/user-attachments/assets/197ec2ab-06df-4416-a3b3-a8aa00a59bfd)

**Comment by johannes-wolf** [comment] 2024-07-28 20:25
Yes, this is due to a precision problem. It has been fixed on `master` with commit 4b089f1.

**Comment by johannes-wolf** [comment] 2024-07-28 20:26
Closing as duplicate of #580.

**Closed by johannes-wolf** 2024-07-28 20:26 UTC

**Comment by leyan** [comment] 2024-07-28 21:23
Indeed it works with the latest master, sorry for the noise I should have checked first.
