### ISSUE TITLE
The behavior of `tree` is different between ver0.2 and ver0.3.

### ISSUE THREAD

**Issue by iwkjosec** [cetz-package/cetz#737] opened 2024-10-28 16:44 UTC
```typ
#import "@preview/cetz:0.2.2" as cetz2
#import "@preview/cetz:0.3.1" as cetz3

#cetz2.canvas(cetz2.tree.tree(([A], [B]), direction: "right"))
#cetz3.canvas(cetz3.tree.tree(([A], [B]), direction: "right"))
```
![image](https://github.com/user-attachments/assets/3b91340c-b5ab-4024-8c7f-3e473f8db20b)

It seems like a bug, but is this an intended change?

**Comment by johannes-wolf** [comment] 2024-11-27 22:36
Duplicate of #754

**Closed by johannes-wolf** 2024-11-27 22:36 UTC
